# wrangler.toml

# The name of your Workers application
name = "Edit Cloudflare Workers"

# Your Cloudflare account ID
account_id = "ba5b63532317d52d0910334a64095a05"

# The kind of application you're deploying to Cloudflare
type = "webpack"

# Publish to workers.dev by default
workers_dev = true